title: The Critical Celtics Fan
email: criticalcelticsfan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We love our team... so much we can't help but critisize them, even when they win. 
  We love watching, cheering, and living every Celtics moment, even the painful ones.

# social links
social_links:
  instagram_username: criticalcelticsfan
  twitter_username: criticalcsfan

show_excerpts: true # set to false to remove excerpts on the homepage

# Google Analytics
google_analytics: G-DSYZFWXV0Y

# theme
remote_theme: jekyll/minima

# plugins
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
