title: The Critical Celtics Fan
email: criticalcelticsfan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We love the Boston Celtics... so much we can't help but critisize them, even when they win. 
  We love watching, cheering, and living every Celtics moment, even the painful ones.

#instagram_username: criticalcelticsfan
# social links
minima:
  social_links:
    instagram: criticalcelticsfan
    twitter: criticalcsfan
#instagram_username: criticalcelticsfan
#twitter_username: criticalcsfan
#author:
#social:
#  instagram: criticalcelticsfan
#  twitter: criticalcsfan

show_excerpts: true # set to false to remove excerpts on the homepage

# Google Analytics
google_analytics: G-DSYZFWXV0Y

# theme
remote_theme: jekyll/minima
#theme: minima

#turn off old code?
#paginate: nil
#paginate_path: nil

# pagination
permalink: /:year/:month/:title.html
pagination:
  enabled: true
  debug: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  #indexpage: 'index'

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: criticalcelticsfan

#for sitemap
url: "https://jrossner.github.io/criticalcelticsfan/"

# plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate-v2
